/**
 * V2 Invariants - Constants and invariant definitions
 * Simple constants only, no logic
 */

// HubSpot Material Order object type
const MATERIAL_ORDER_TYPE = "2-22239999";

// Status constants
const STATUS_DRAFT = "DRAFT";
const STATUS_PROCESSING = "PROCESSING";
const STATUS_SUBMITTED = "SUBMITTED";
const STATUS_FAILED = "FAILED";

// Allowed status transitions
const ALLOWED_TRANSITIONS = {
  [STATUS_DRAFT]: [STATUS_PROCESSING, STATUS_FAILED],
  [STATUS_PROCESSING]: [STATUS_SUBMITTED, STATUS_FAILED],
  [STATUS_SUBMITTED]: [], // Terminal state
  [STATUS_FAILED]: [], // Terminal state
};

// HubSpot property names
const PROP_EXTERNAL_KEY = "external_key";
const PROP_PAYLOAD_SNAPSHOT = "payload_snapshot";
const PROP_STATUS = "status";
const PROP_ENV = "env";
const PROP_SUPPLIER_KEY = "supplier_key";
const PROP_PDF_URL = "order_url";
const PROP_STATUS_REASON = "status_reason";

// Receipt kinds
const RECEIPT_KIND_LOGIN = "LOGIN";
const RECEIPT_KIND_PRICING = "PRICING";
const RECEIPT_KIND_ORDER = "ORDER";
const RECEIPT_KIND_ORDER_DRY_RUN = "ORDER_DRY_RUN";
const RECEIPT_KIND_SEARCH = "SEARCH";
const RECEIPT_KIND_HUBSPOT_DRAFT = "HUBSPOT_DRAFT";
const RECEIPT_KIND_SUBMIT_PIPELINE = "SUBMIT_PIPELINE";

// Error codes
const ERROR_CODE_PROD_ORDER_LOCKED = "PROD_ORDER_LOCKED";
const ERROR_CODE_MISSING_CONTEXT = "MISSING_CONTEXT";
const ERROR_CODE_INVALID_ENV = "INVALID_ENV";
const ERROR_CODE_INVALID_SUPPLIER = "INVALID_SUPPLIER";

module.exports = {
  MATERIAL_ORDER_TYPE,
  STATUS_DRAFT,
  STATUS_PROCESSING,
  STATUS_SUBMITTED,
  STATUS_FAILED,
  ALLOWED_TRANSITIONS,
  PROP_EXTERNAL_KEY,
  PROP_PAYLOAD_SNAPSHOT,
  PROP_STATUS,
  PROP_ENV,
  PROP_SUPPLIER_KEY,
  PROP_PDF_URL,
  PROP_STATUS_REASON,
  RECEIPT_KIND_LOGIN,
  RECEIPT_KIND_PRICING,
  RECEIPT_KIND_ORDER,
  RECEIPT_KIND_ORDER_DRY_RUN,
  RECEIPT_KIND_SEARCH,
  RECEIPT_KIND_HUBSPOT_DRAFT,
  RECEIPT_KIND_SUBMIT_PIPELINE,
  ERROR_CODE_PROD_ORDER_LOCKED,
  ERROR_CODE_MISSING_CONTEXT,
  ERROR_CODE_INVALID_ENV,
  ERROR_CODE_INVALID_SUPPLIER,
};
